version: '3'

volumes:
  pg_data_cattygram:
  static_cattygram:
  media_cattygram:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_cattygram:/backend_static/
      - media_cattygram:/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_cattygram:/frontend_static

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_cattygram:/staticfiles
      - media_cattygram:/media/
    depends_on:
      - backend
